### ISSUE TITLE
Feature Request: disable for unconscious units

### ISSUE THREAD

**Issue by Codingboy** [BaerMitUmlaut/BlueHud#2]
Disable the icons in the BlueHud for unconscious units (ACE).

**Comment by BaerMitUmlaut** [comment]
I could do that, but then if somebody is suddenly disappearing from the HUD you know that he just fell unconscious, so I'd rather leave that as it is.

**Comment by Codingboy** [comment]
I know what you mean. Would it be to much work to implement this with a fading.
I mentioned this featurerequest because I used sthud also for finding "dead" players.
Your hud has a much shorter range but it may still be used as searchradar in high grass.

btw.: I am also from germany ;)
and very good work so far

**Comment by BaerMitUmlaut** [comment]
I could implement it on a different branch and you could download it from there? You'd have to compile your own version though.

**Comment by Codingboy** [comment]
would be nice, thanks!

**Comment by BaerMitUmlaut** [comment]
Here you go: https://github.com/BaerMitUmlaut/BlueHud/tree/displayUnconscious
It's only a really small change as you might see. It's compatible with ACE 3, AGM and probably CSE, too.
