### ISSUE TITLE
Feature request thread

### ISSUE THREAD

**Issue by gienkov** [BaerMitUmlaut/BlueHud#3]
Enable HUD when inside vehicle too, it works like that in STHud I think, you have somewhat larger HUD range.

**Comment by BaerMitUmlaut** [comment]
You have even less or no periphal vision inside a vehicle (depending on the type of the vehicle) and especially don't know what's going on behind your vehicle. This is why it has been disabled in vehicles on purpose.

**Comment by gienkov** [comment]
Legit.
